import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Course from '../models/Course.js';

dotenv.config();

const courses = [
  // Artificial Intelligence
  {
    courseId: 'ai-fundamentals-2024',
    title: 'Artificial Intelligence Fundamentals',
    description: 'Master the foundations of AI including neural networks, machine learning algorithms, and practical applications. Learn how to build intelligent systems from scratch.',
    shortDescription: 'Complete introduction to AI concepts, neural networks, and practical applications',
    category: 'Artificial Intelligence',
    subcategory: 'AI Basics',
    difficulty: 'Beginner',
    duration: { hours: 40, minutes: 0 },
    instructor: { name: 'Dr. Andrew Ng', title: 'AI Researcher' },
    videoUrl: 'https://www.youtube.com/watch?v=aircAruvnKk',
    thumbnailUrl: 'https://img.youtube.com/vi/aircAruvnKk/maxresdefault.jpg',
    tags: ['AI', 'Neural Networks', 'Deep Learning', 'Python'],
    skills: ['Neural Networks', 'AI Algorithms', 'Python Programming'],
    prerequisites: ['Basic Python', 'Mathematics'],
    learningOutcomes: ['Understand AI concepts', 'Build neural networks', 'Implement AI algorithms'],
    rating: { average: 4.8, count: 12450 },
    enrollments: 45230,
    featured: true
  },
  {
    courseId: 'deep-learning-specialization',
    title: 'Deep Learning Specialization',
    description: 'Advanced deep learning course covering CNNs, RNNs, LSTMs, and Transformers. Build state-of-the-art AI models.',
    shortDescription: 'Advanced deep learning with CNNs, RNNs, and Transformers',
    category: 'Artificial Intelligence',
    subcategory: 'Deep Learning',
    difficulty: 'Advanced',
    duration: { hours: 60, minutes: 0 },
    instructor: { name: 'Dr. Yoshua Bengio', title: 'Deep Learning Pioneer' },
    videoUrl: 'https://www.youtube.com/watch?v=CS4cs9xVecg',
    thumbnailUrl: 'https://img.youtube.com/vi/CS4cs9xVecg/maxresdefault.jpg',
    tags: ['Deep Learning', 'CNN', 'RNN', 'Transformers', 'PyTorch'],
    skills: ['CNNs', 'RNNs', 'Transformers', 'PyTorch'],
    prerequisites: ['Neural Networks', 'Python', 'Linear Algebra'],
    learningOutcomes: ['Master deep learning architectures', 'Build advanced models', 'Deploy AI systems'],
    rating: { average: 4.9, count: 8920 },
    enrollments: 32100,
    featured: true
  },
  {
    courseId: 'computer-vision-masterclass',
    title: 'Computer Vision Masterclass',
    description: 'Learn image processing, object detection, face recognition, and image segmentation using modern AI techniques.',
    shortDescription: 'Complete computer vision course with hands-on projects',
    category: 'Artificial Intelligence',
    subcategory: 'Computer Vision',
    difficulty: 'Intermediate',
    duration: { hours: 45, minutes: 30 },
    instructor: { name: 'Fei-Fei Li', title: 'Computer Vision Expert' },
    videoUrl: 'https://www.youtube.com/watch?v=dJYGatp4SvA',
    thumbnailUrl: 'https://img.youtube.com/vi/dJYGatp4SvA/maxresdefault.jpg',
    tags: ['Computer Vision', 'OpenCV', 'Image Processing', 'Object Detection'],
    skills: ['Image Processing', 'Object Detection', 'OpenCV', 'TensorFlow'],
    prerequisites: ['Python', 'Basic Machine Learning'],
    learningOutcomes: ['Build CV applications', 'Implement object detection', 'Work with image data'],
    rating: { average: 4.7, count: 5680 },
    enrollments: 18900
  },

  // Machine Learning
  {
    courseId: 'ml-crash-course-2024',
    title: 'Machine Learning Crash Course',
    description: 'Fast-track your ML journey with this comprehensive course covering supervised, unsupervised, and reinforcement learning.',
    shortDescription: 'Complete ML fundamentals with practical projects',
    category: 'Machine Learning',
    subcategory: 'ML Basics',
    difficulty: 'Beginner',
    duration: { hours: 35, minutes: 0 },
    instructor: { name: 'Sebastian Thrun', title: 'ML Expert' },
    videoUrl: 'https://www.youtube.com/watch?v=ukzFI9rgwfU',
    thumbnailUrl: 'https://img.youtube.com/vi/ukzFI9rgwfU/maxresdefault.jpg',
    tags: ['Machine Learning', 'Supervised Learning', 'Unsupervised Learning', 'Scikit-learn'],
    skills: ['ML Algorithms', 'Data Preprocessing', 'Model Training', 'Scikit-learn'],
    prerequisites: ['Python', 'Basic Statistics'],
    learningOutcomes: ['Understand ML algorithms', 'Build ML models', 'Deploy models'],
    rating: { average: 4.8, count: 15200 },
    enrollments: 52400,
    featured: true
  },
  {
    courseId: 'advanced-ml-algorithms',
    title: 'Advanced Machine Learning Algorithms',
    description: 'Deep dive into advanced ML algorithms including ensemble methods, gradient boosting, and neural networks.',
    shortDescription: 'Master advanced ML techniques and ensemble methods',
    category: 'Machine Learning',
    subcategory: 'Advanced ML',
    difficulty: 'Advanced',
    duration: { hours: 50, minutes: 0 },
    instructor: { name: 'Geoffrey Hinton', title: 'ML Pioneer' },
    videoUrl: 'https://www.youtube.com/watch?v=jGwO_UgTS7I',
    thumbnailUrl: 'https://img.youtube.com/vi/jGwO_UgTS7I/maxresdefault.jpg',
    tags: ['Advanced ML', 'Ensemble Methods', 'Gradient Boosting', 'XGBoost'],
    skills: ['Ensemble Methods', 'Gradient Boosting', 'Feature Engineering', 'Model Optimization'],
    prerequisites: ['ML Basics', 'Python', 'Statistics'],
    learningOutcomes: ['Master advanced algorithms', 'Optimize models', 'Handle complex datasets'],
    rating: { average: 4.9, count: 6780 },
    enrollments: 23100
  },

  // Data Science
  {
    courseId: 'data-science-complete',
    title: 'Complete Data Science Bootcamp',
    description: 'Comprehensive data science course covering Python, statistics, ML, data visualization, and real-world projects.',
    shortDescription: 'Full-stack data science with Python and ML',
    category: 'Data Science',
    subcategory: 'Data Science Fundamentals',
    difficulty: 'Beginner',
    duration: { hours: 55, minutes: 0 },
    instructor: { name: 'Jose Portilla', title: 'Data Science Instructor' },
    videoUrl: 'https://www.youtube.com/watch?v=LHBE6Q9XlzI',
    thumbnailUrl: 'https://img.youtube.com/vi/LHBE6Q9XlzI/maxresdefault.jpg',
    tags: ['Data Science', 'Python', 'Pandas', 'NumPy', 'Matplotlib'],
    skills: ['Data Analysis', 'Python', 'Pandas', 'Data Visualization', 'Statistics'],
    prerequisites: ['Basic Programming'],
    learningOutcomes: ['Analyze data', 'Create visualizations', 'Build predictive models'],
    rating: { average: 4.7, count: 18900 },
    enrollments: 67800,
    featured: true
  },
  {
    courseId: 'data-analysis-python',
    title: 'Data Analysis with Python',
    description: 'Learn data manipulation, cleaning, and analysis using Python, Pandas, and NumPy with real datasets.',
    shortDescription: 'Master data analysis with Pandas and NumPy',
    category: 'Data Science',
    subcategory: 'Data Analysis',
    difficulty: 'Intermediate',
    duration: { hours: 30, minutes: 0 },
    instructor: { name: 'Hadley Wickham', title: 'Data Scientist' },
    videoUrl: 'https://www.youtube.com/watch?v=vmEHCJofslg',
    thumbnailUrl: 'https://img.youtube.com/vi/vmEHCJofslg/maxresdefault.jpg',
    tags: ['Data Analysis', 'Pandas', 'NumPy', 'Python'],
    skills: ['Data Cleaning', 'Data Manipulation', 'Pandas', 'NumPy'],
    prerequisites: ['Python Basics'],
    learningOutcomes: ['Clean messy data', 'Perform exploratory analysis', 'Extract insights'],
    rating: { average: 4.6, count: 9870 },
    enrollments: 34500
  },
  {
    courseId: 'data-visualization-masterclass',
    title: 'Data Visualization Masterclass',
    description: 'Create stunning visualizations using Matplotlib, Seaborn, Plotly, and Tableau.',
    shortDescription: 'Create professional data visualizations',
    category: 'Data Science',
    subcategory: 'Data Visualization',
    difficulty: 'Intermediate',
    duration: { hours: 25, minutes: 0 },
    instructor: { name: 'Edward Tufte', title: 'Visualization Expert' },
    videoUrl: 'https://www.youtube.com/watch?v=_ZEWDGpM-vM',
    thumbnailUrl: 'https://img.youtube.com/vi/_ZEWDGpM-vM/maxresdefault.jpg',
    tags: ['Data Visualization', 'Matplotlib', 'Seaborn', 'Plotly', 'Tableau'],
    skills: ['Matplotlib', 'Seaborn', 'Plotly', 'Dashboard Creation'],
    prerequisites: ['Python', 'Data Analysis'],
    learningOutcomes: ['Create interactive visualizations', 'Build dashboards', 'Tell data stories'],
    rating: { average: 4.8, count: 7230 },
    enrollments: 28900
  },

  // Web Development
  {
    courseId: 'fullstack-web-dev-2024',
    title: 'Full Stack Web Development 2024',
    description: 'Complete web development course covering HTML, CSS, JavaScript, React, Node.js, and MongoDB.',
    shortDescription: 'Become a full stack developer with MERN stack',
    category: 'Web Development',
    subcategory: 'Full Stack',
    difficulty: 'Beginner',
    duration: { hours: 70, minutes: 0 },
    instructor: { name: 'Brad Traversy', title: 'Web Developer' },
    videoUrl: 'https://www.youtube.com/watch?v=nu_pCVPKzTk',
    thumbnailUrl: 'https://img.youtube.com/vi/nu_pCVPKzTk/maxresdefault.jpg',
    tags: ['Web Development', 'React', 'Node.js', 'MongoDB', 'Express'],
    skills: ['React', 'Node.js', 'MongoDB', 'Express', 'REST APIs'],
    prerequisites: ['Basic HTML/CSS'],
    learningOutcomes: ['Build full stack apps', 'Create REST APIs', 'Deploy web applications'],
    rating: { average: 4.9, count: 25600 },
    enrollments: 89700,
    featured: true
  },
  {
    courseId: 'react-complete-guide',
    title: 'React - The Complete Guide 2024',
    description: 'Master React including hooks, context, Redux, Next.js, and advanced patterns.',
    shortDescription: 'Complete React course with hooks and Redux',
    category: 'Web Development',
    subcategory: 'Frontend',
    difficulty: 'Intermediate',
    duration: { hours: 48, minutes: 30 },
    instructor: { name: 'Maximilian Schwarzmüller', title: 'React Expert' },
    videoUrl: 'https://www.youtube.com/watch?v=Ke90Tje7VS0',
    thumbnailUrl: 'https://img.youtube.com/vi/Ke90Tje7VS0/maxresdefault.jpg',
    tags: ['React', 'Hooks', 'Redux', 'Next.js', 'JavaScript'],
    skills: ['React', 'Hooks', 'Redux', 'State Management', 'Next.js'],
    prerequisites: ['JavaScript', 'HTML/CSS'],
    learningOutcomes: ['Master React', 'Build SPAs', 'Manage complex state'],
    rating: { average: 4.8, count: 19800 },
    enrollments: 72300,
    featured: true
  },
  {
    courseId: 'nodejs-backend-dev',
    title: 'Node.js Backend Development',
    description: 'Build scalable backend applications with Node.js, Express, MongoDB, and authentication.',
    shortDescription: 'Backend development with Node.js and Express',
    category: 'Web Development',
    subcategory: 'Backend',
    difficulty: 'Intermediate',
    duration: { hours: 42, minutes: 0 },
    instructor: { name: 'Wes Bos', title: 'Full Stack Developer' },
    videoUrl: 'https://www.youtube.com/watch?v=Oe421EPjeBE',
    thumbnailUrl: 'https://img.youtube.com/vi/Oe421EPjeBE/maxresdefault.jpg',
    tags: ['Node.js', 'Express', 'MongoDB', 'REST API', 'Authentication'],
    skills: ['Node.js', 'Express', 'MongoDB', 'JWT', 'REST APIs'],
    prerequisites: ['JavaScript'],
    learningOutcomes: ['Build REST APIs', 'Implement authentication', 'Work with databases'],
    rating: { average: 4.7, count: 14500 },
    enrollments: 48900
  },

  // Game Development
  {
    courseId: 'unity-game-dev-complete',
    title: 'Complete Unity Game Development',
    description: 'Learn Unity from scratch and create 2D and 3D games. Master C# programming and game design.',
    shortDescription: 'Create games with Unity and C#',
    category: 'Game Development',
    subcategory: 'Unity',
    difficulty: 'Beginner',
    duration: { hours: 65, minutes: 0 },
    instructor: { name: 'Ben Tristem', title: 'Game Developer' },
    videoUrl: 'https://www.youtube.com/watch?v=gB1F9G0JXOo',
    thumbnailUrl: 'https://img.youtube.com/vi/gB1F9G0JXOo/maxresdefault.jpg',
    tags: ['Unity', 'Game Development', 'C#', '3D Games', '2D Games'],
    skills: ['Unity', 'C#', 'Game Design', '3D Modeling', 'Physics'],
    prerequisites: ['Basic Programming'],
    learningOutcomes: ['Build 2D/3D games', 'Master Unity', 'Publish games'],
    rating: { average: 4.8, count: 16700 },
    enrollments: 56800,
    featured: true
  },
  {
    courseId: 'unreal-engine-5-course',
    title: 'Unreal Engine 5 Complete Course',
    description: 'Master Unreal Engine 5 and create stunning 3D games with blueprints and C++.',
    shortDescription: 'Build AAA games with Unreal Engine 5',
    category: 'Game Development',
    subcategory: 'Unreal Engine',
    difficulty: 'Intermediate',
    duration: { hours: 58, minutes: 30 },
    instructor: { name: 'Epic Games Team', title: 'Game Developers' },
    videoUrl: 'https://www.youtube.com/watch?v=k-zMkzmduqI',
    thumbnailUrl: 'https://img.youtube.com/vi/k-zMkzmduqI/maxresdefault.jpg',
    tags: ['Unreal Engine', 'Game Development', 'Blueprints', 'C++', '3D Games'],
    skills: ['Unreal Engine 5', 'Blueprints', 'C++', 'Level Design', 'Game Mechanics'],
    prerequisites: ['Basic Programming', 'Game Design Concepts'],
    learningOutcomes: ['Create AAA games', 'Master UE5', 'Implement game mechanics'],
    rating: { average: 4.9, count: 11200 },
    enrollments: 38900
  },
  {
    courseId: 'game-design-fundamentals',
    title: 'Game Design Fundamentals',
    description: 'Learn the principles of game design, mechanics, player psychology, and level design.',
    shortDescription: 'Master game design theory and practice',
    category: 'Game Development',
    subcategory: 'Game Design',
    difficulty: 'Beginner',
    duration: { hours: 32, minutes: 0 },
    instructor: { name: 'Jesse Schell', title: 'Game Designer' },
    videoUrl: 'https://www.youtube.com/watch?v=z06QR-tz1_o',
    thumbnailUrl: 'https://img.youtube.com/vi/z06QR-tz1_o/maxresdefault.jpg',
    tags: ['Game Design', 'Game Mechanics', 'Level Design', 'Player Psychology'],
    skills: ['Game Mechanics', 'Level Design', 'Player Experience', 'Game Balance'],
    prerequisites: ['None'],
    learningOutcomes: ['Design engaging games', 'Create balanced mechanics', 'Understand player psychology'],
    rating: { average: 4.7, count: 8900 },
    enrollments: 29400
  },

  // Programming Languages - Python
  {
    courseId: 'python-complete-bootcamp',
    title: 'Complete Python Bootcamp 2024',
    description: 'Learn Python from zero to hero with hands-on projects and real-world applications.',
    shortDescription: 'Master Python programming from scratch',
    category: 'Programming Languages',
    subcategory: 'Python',
    difficulty: 'Beginner',
    duration: { hours: 45, minutes: 0 },
    instructor: { name: 'Corey Schafer', title: 'Python Expert' },
    videoUrl: 'https://www.youtube.com/watch?v=rfscVS0vtbw',
    thumbnailUrl: 'https://img.youtube.com/vi/rfscVS0vtbw/maxresdefault.jpg',
    tags: ['Python', 'Programming', 'OOP', 'Data Structures'],
    skills: ['Python', 'OOP', 'Data Structures', 'File Handling', 'APIs'],
    prerequisites: ['None'],
    learningOutcomes: ['Write Python programs', 'Build applications', 'Work with data'],
    rating: { average: 4.9, count: 32100 },
    enrollments: 112400,
    featured: true
  },
  {
    courseId: 'advanced-python-programming',
    title: 'Advanced Python Programming',
    description: 'Master advanced Python concepts including decorators, generators, context managers, and async programming.',
    shortDescription: 'Advanced Python techniques and patterns',
    category: 'Programming Languages',
    subcategory: 'Python',
    difficulty: 'Advanced',
    duration: { hours: 38, minutes: 0 },
    instructor: { name: 'Raymond Hettinger', title: 'Python Core Developer' },
    videoUrl: 'https://www.youtube.com/watch?v=OSGv2VnC0go',
    thumbnailUrl: 'https://img.youtube.com/vi/OSGv2VnC0go/maxresdefault.jpg',
    tags: ['Python', 'Advanced', 'Decorators', 'Generators', 'Async'],
    skills: ['Decorators', 'Generators', 'Context Managers', 'Async/Await', 'Metaclasses'],
    prerequisites: ['Python Basics', 'OOP'],
    learningOutcomes: ['Master advanced concepts', 'Write efficient code', 'Use design patterns'],
    rating: { average: 4.8, count: 9870 },
    enrollments: 32800
  },

  // Mobile Development
  {
    courseId: 'react-native-complete',
    title: 'React Native - Complete Mobile App Development',
    description: 'Build cross-platform mobile apps for iOS and Android using React Native.',
    shortDescription: 'Create mobile apps with React Native',
    category: 'Mobile Development',
    subcategory: 'React Native',
    difficulty: 'Intermediate',
    duration: { hours: 52, minutes: 0 },
    instructor: { name: 'Stephen Grider', title: 'Mobile Developer' },
    videoUrl: 'https://www.youtube.com/watch?v=0-S5a0eXPoc',
    thumbnailUrl: 'https://img.youtube.com/vi/0-S5a0eXPoc/maxresdefault.jpg',
    tags: ['React Native', 'Mobile Development', 'iOS', 'Android', 'JavaScript'],
    skills: ['React Native', 'Mobile UI', 'Navigation', 'State Management', 'APIs'],
    prerequisites: ['React', 'JavaScript'],
    learningOutcomes: ['Build mobile apps', 'Publish to app stores', 'Handle device features'],
    rating: { average: 4.7, count: 13400 },
    enrollments: 45600
  },
  {
    courseId: 'flutter-app-development',
    title: 'Flutter & Dart Complete Course',
    description: 'Learn Flutter and Dart to build beautiful native mobile apps for iOS and Android.',
    shortDescription: 'Build native apps with Flutter',
    category: 'Mobile Development',
    subcategory: 'Flutter',
    difficulty: 'Beginner',
    duration: { hours: 48, minutes: 0 },
    instructor: { name: 'Maximilian Schwarzmüller', title: 'Flutter Expert' },
    videoUrl: 'https://www.youtube.com/watch?v=x0uinJvhNxI',
    thumbnailUrl: 'https://img.youtube.com/vi/x0uinJvhNxI/maxresdefault.jpg',
    tags: ['Flutter', 'Dart', 'Mobile Development', 'iOS', 'Android'],
    skills: ['Flutter', 'Dart', 'Mobile UI', 'State Management', 'Firebase'],
    prerequisites: ['Basic Programming'],
    learningOutcomes: ['Build Flutter apps', 'Master Dart', 'Deploy to stores'],
    rating: { average: 4.8, count: 17800 },
    enrollments: 61200,
    featured: true
  },

  // Cloud Computing
  {
    courseId: 'aws-certified-solutions-architect',
    title: 'AWS Certified Solutions Architect',
    description: 'Complete AWS certification preparation covering EC2, S3, Lambda, RDS, and cloud architecture.',
    shortDescription: 'AWS certification prep and cloud architecture',
    category: 'Cloud Computing',
    subcategory: 'AWS',
    difficulty: 'Intermediate',
    duration: { hours: 55, minutes: 0 },
    instructor: { name: 'Stephane Maarek', title: 'AWS Expert' },
    videoUrl: 'https://www.youtube.com/watch?v=Ia-UEYYR44s',
    thumbnailUrl: 'https://img.youtube.com/vi/Ia-UEYYR44s/maxresdefault.jpg',
    tags: ['AWS', 'Cloud Computing', 'EC2', 'S3', 'Lambda'],
    skills: ['AWS Services', 'Cloud Architecture', 'EC2', 'S3', 'Serverless'],
    prerequisites: ['Networking Basics', 'Linux'],
    learningOutcomes: ['Pass AWS certification', 'Design cloud solutions', 'Deploy applications'],
    rating: { average: 4.9, count: 22300 },
    enrollments: 78900,
    featured: true
  },
  {
    courseId: 'azure-fundamentals',
    title: 'Microsoft Azure Fundamentals',
    description: 'Learn Azure cloud services including compute, storage, networking, and AI services.',
    shortDescription: 'Master Microsoft Azure cloud platform',
    category: 'Cloud Computing',
    subcategory: 'Azure',
    difficulty: 'Beginner',
    duration: { hours: 42, minutes: 0 },
    instructor: { name: 'Scott Duffy', title: 'Azure Architect' },
    videoUrl: 'https://www.youtube.com/watch?v=NKEFWyqJ5XA',
    thumbnailUrl: 'https://img.youtube.com/vi/NKEFWyqJ5XA/maxresdefault.jpg',
    tags: ['Azure', 'Cloud Computing', 'Microsoft', 'Cloud Services'],
    skills: ['Azure Services', 'Virtual Machines', 'Storage', 'Networking', 'DevOps'],
    prerequisites: ['Basic IT Knowledge'],
    learningOutcomes: ['Use Azure services', 'Deploy cloud solutions', 'Pass AZ-900'],
    rating: { average: 4.7, count: 15600 },
    enrollments: 52300
  },

  // Cybersecurity
  {
    courseId: 'ethical-hacking-complete',
    title: 'Complete Ethical Hacking Course',
    description: 'Learn penetration testing, vulnerability assessment, and cybersecurity fundamentals.',
    shortDescription: 'Ethical hacking and penetration testing',
    category: 'Cybersecurity',
    subcategory: 'Ethical Hacking',
    difficulty: 'Intermediate',
    duration: { hours: 62, minutes: 0 },
    instructor: { name: 'Zaid Sabih', title: 'Cybersecurity Expert' },
    videoUrl: 'https://www.youtube.com/watch?v=3Kq1MIfTWCE',
    thumbnailUrl: 'https://img.youtube.com/vi/3Kq1MIfTWCE/maxresdefault.jpg',
    tags: ['Ethical Hacking', 'Penetration Testing', 'Security', 'Kali Linux'],
    skills: ['Penetration Testing', 'Network Security', 'Web Security', 'Kali Linux'],
    prerequisites: ['Networking', 'Linux Basics'],
    learningOutcomes: ['Perform penetration tests', 'Find vulnerabilities', 'Secure systems'],
    rating: { average: 4.8, count: 14200 },
    enrollments: 47800,
    featured: true
  },
  {
    courseId: 'cybersecurity-fundamentals',
    title: 'Cybersecurity Fundamentals',
    description: 'Essential cybersecurity concepts including threat analysis, risk management, and security best practices.',
    shortDescription: 'Essential cybersecurity for beginners',
    category: 'Cybersecurity',
    subcategory: 'Security Basics',
    difficulty: 'Beginner',
    duration: { hours: 35, minutes: 0 },
    instructor: { name: 'CompTIA Team', title: 'Security Experts' },
    videoUrl: 'https://www.youtube.com/watch?v=sdpxddDzXfE',
    thumbnailUrl: 'https://img.youtube.com/vi/sdpxddDzXfE/maxresdefault.jpg',
    tags: ['Cybersecurity', 'Security', 'Network Security', 'CompTIA'],
    skills: ['Security Fundamentals', 'Threat Analysis', 'Risk Management', 'Cryptography'],
    prerequisites: ['Basic IT Knowledge'],
    learningOutcomes: ['Understand security concepts', 'Identify threats', 'Implement security measures'],
    rating: { average: 4.6, count: 11800 },
    enrollments: 39200
  },

  // DevOps
  {
    courseId: 'docker-kubernetes-complete',
    title: 'Docker and Kubernetes Complete Guide',
    description: 'Master containerization with Docker and orchestration with Kubernetes for modern DevOps.',
    shortDescription: 'Container orchestration with Docker & Kubernetes',
    category: 'DevOps',
    subcategory: 'Containers',
    difficulty: 'Intermediate',
    duration: { hours: 46, minutes: 0 },
    instructor: { name: 'Bret Fisher', title: 'DevOps Expert' },
    videoUrl: 'https://www.youtube.com/watch?v=3c-iBn73dDE',
    thumbnailUrl: 'https://img.youtube.com/vi/3c-iBn73dDE/maxresdefault.jpg',
    tags: ['Docker', 'Kubernetes', 'DevOps', 'Containers', 'Orchestration'],
    skills: ['Docker', 'Kubernetes', 'Container Orchestration', 'CI/CD', 'Microservices'],
    prerequisites: ['Linux', 'Basic Networking'],
    learningOutcomes: ['Deploy containers', 'Orchestrate with K8s', 'Build CI/CD pipelines'],
    rating: { average: 4.9, count: 18700 },
    enrollments: 64200,
    featured: true
  },

  // Blockchain
  {
    courseId: 'blockchain-ethereum-solidity',
    title: 'Blockchain & Ethereum Development',
    description: 'Build decentralized applications (DApps) with Ethereum, Solidity, and Web3.js.',
    shortDescription: 'Create DApps with Ethereum and Solidity',
    category: 'Blockchain',
    subcategory: 'Ethereum',
    difficulty: 'Advanced',
    duration: { hours: 52, minutes: 0 },
    instructor: { name: 'Vitalik Buterin', title: 'Ethereum Founder' },
    videoUrl: 'https://www.youtube.com/watch?v=M576WGiDBdQ',
    thumbnailUrl: 'https://img.youtube.com/vi/M576WGiDBdQ/maxresdefault.jpg',
    tags: ['Blockchain', 'Ethereum', 'Solidity', 'Smart Contracts', 'DApps'],
    skills: ['Solidity', 'Smart Contracts', 'Web3.js', 'DApp Development', 'Ethereum'],
    prerequisites: ['JavaScript', 'Basic Cryptography'],
    learningOutcomes: ['Build smart contracts', 'Create DApps', 'Deploy on Ethereum'],
    rating: { average: 4.7, count: 9200 },
    enrollments: 31400
  },

  // UI/UX Design
  {
    courseId: 'ui-ux-design-complete',
    title: 'Complete UI/UX Design Course',
    description: 'Learn user experience design, user interface design, and design thinking with Figma.',
    shortDescription: 'Master UI/UX design with Figma',
    category: 'UI/UX Design',
    subcategory: 'UI/UX Basics',
    difficulty: 'Beginner',
    duration: { hours: 40, minutes: 0 },
    instructor: { name: 'Daniel Walter Scott', title: 'UX Designer' },
    videoUrl: 'https://www.youtube.com/watch?v=c9Wg6Cb_YlU',
    thumbnailUrl: 'https://img.youtube.com/vi/c9Wg6Cb_YlU/maxresdefault.jpg',
    tags: ['UI/UX', 'Design', 'Figma', 'User Experience', 'User Interface'],
    skills: ['UI Design', 'UX Design', 'Figma', 'Prototyping', 'User Research'],
    prerequisites: ['None'],
    learningOutcomes: ['Design beautiful interfaces', 'Create prototypes', 'Conduct user research'],
    rating: { average: 4.8, count: 16900 },
    enrollments: 58700,
    featured: true
  },

  // Database
  {
    courseId: 'mongodb-complete-guide',
    title: 'MongoDB Complete Developer Guide',
    description: 'Master MongoDB including data modeling, aggregation, indexing, and performance optimization.',
    shortDescription: 'Complete MongoDB for developers',
    category: 'Database',
    subcategory: 'NoSQL',
    difficulty: 'Intermediate',
    duration: { hours: 38, minutes: 0 },
    instructor: { name: 'Eliot Horowitz', title: 'MongoDB Expert' },
    videoUrl: 'https://www.youtube.com/watch?v=-56x56UppqQ',
    thumbnailUrl: 'https://img.youtube.com/vi/-56x56UppqQ/maxresdefault.jpg',
    tags: ['MongoDB', 'NoSQL', 'Database', 'Data Modeling'],
    skills: ['MongoDB', 'Data Modeling', 'Aggregation', 'Indexing', 'Performance'],
    prerequisites: ['Basic Database Concepts'],
    learningOutcomes: ['Design MongoDB schemas', 'Optimize queries', 'Build scalable databases'],
    rating: { average: 4.7, count: 12400 },
    enrollments: 42800
  },
  {
    courseId: 'sql-mysql-complete',
    title: 'Complete SQL and MySQL Bootcamp',
    description: 'Master SQL from basics to advanced including joins, subqueries, and database design.',
    shortDescription: 'Master SQL and MySQL',
    category: 'Database',
    subcategory: 'SQL',
    difficulty: 'Beginner',
    duration: { hours: 32, minutes: 0 },
    instructor: { name: 'Colt Steele', title: 'Database Expert' },
    videoUrl: 'https://www.youtube.com/watch?v=HXV3zeQKqGY',
    thumbnailUrl: 'https://img.youtube.com/vi/HXV3zeQKqGY/maxresdefault.jpg',
    tags: ['SQL', 'MySQL', 'Database', 'Queries', 'Database Design'],
    skills: ['SQL', 'MySQL', 'Database Design', 'Joins', 'Stored Procedures'],
    prerequisites: ['None'],
    learningOutcomes: ['Write complex queries', 'Design databases', 'Optimize performance'],
    rating: { average: 4.8, count: 19200 },
    enrollments: 67800,
    featured: true
  },

  // Additional AI Courses
  {
    courseId: 'nlp-natural-language-processing',
    title: 'Natural Language Processing with Python',
    description: 'Master NLP techniques including tokenization, sentiment analysis, named entity recognition, and transformers.',
    shortDescription: 'NLP from basics to transformers',
    category: 'Artificial Intelligence',
    subcategory: 'NLP',
    difficulty: 'Advanced',
    duration: { hours: 48, minutes: 0 },
    instructor: { name: 'Dan Jurafsky', title: 'NLP Expert' },
    videoUrl: 'https://www.youtube.com/watch?v=8rXD5-xhemo',
    thumbnailUrl: 'https://img.youtube.com/vi/8rXD5-xhemo/maxresdefault.jpg',
    tags: ['NLP', 'AI', 'Transformers', 'BERT', 'Text Processing'],
    skills: ['NLP', 'NLTK', 'spaCy', 'Transformers', 'BERT'],
    prerequisites: ['Python', 'ML Basics'],
    learningOutcomes: ['Build NLP models', 'Work with text data', 'Use transformers'],
    rating: { average: 4.8, count: 7890 },
    enrollments: 28700
  },
  {
    courseId: 'reinforcement-learning-ai',
    title: 'Reinforcement Learning Complete Course',
    description: 'Learn RL algorithms, Q-learning, policy gradients, and deep reinforcement learning.',
    shortDescription: 'Master reinforcement learning algorithms',
    category: 'Artificial Intelligence',
    subcategory: 'Reinforcement Learning',
    difficulty: 'Advanced',
    duration: { hours: 42, minutes: 0 },
    instructor: { name: 'David Silver', title: 'DeepMind Researcher' },
    videoUrl: 'https://www.youtube.com/watch?v=2pWv7GOvuf0',
    thumbnailUrl: 'https://img.youtube.com/vi/2pWv7GOvuf0/maxresdefault.jpg',
    tags: ['Reinforcement Learning', 'Q-Learning', 'Deep RL', 'AI'],
    skills: ['RL Algorithms', 'Q-Learning', 'Policy Gradients', 'OpenAI Gym'],
    prerequisites: ['ML Basics', 'Python'],
    learningOutcomes: ['Build RL agents', 'Implement RL algorithms', 'Train game AI'],
    rating: { average: 4.9, count: 5670 },
    enrollments: 19800
  },

  // Additional Web Development Courses
  {
    courseId: 'vue-js-complete-course',
    title: 'Vue.js 3 - The Complete Guide',
    description: 'Master Vue.js 3 with Composition API, Vuex, Vue Router, and build modern web applications.',
    shortDescription: 'Complete Vue.js 3 course',
    category: 'Web Development',
    subcategory: 'Frontend',
    difficulty: 'Intermediate',
    duration: { hours: 44, minutes: 0 },
    instructor: { name: 'Evan You', title: 'Vue.js Creator' },
    videoUrl: 'https://www.youtube.com/watch?v=FXpIoQ_rT_c',
    thumbnailUrl: 'https://img.youtube.com/vi/FXpIoQ_rT_c/maxresdefault.jpg',
    tags: ['Vue.js', 'JavaScript', 'Frontend', 'Vuex', 'Vue Router'],
    skills: ['Vue.js 3', 'Composition API', 'Vuex', 'Vue Router', 'Component Design'],
    prerequisites: ['JavaScript', 'HTML/CSS'],
    learningOutcomes: ['Build Vue apps', 'Master Composition API', 'Manage state'],
    rating: { average: 4.7, count: 11200 },
    enrollments: 38900
  },
  {
    courseId: 'angular-complete-guide',
    title: 'Angular - The Complete Guide 2024',
    description: 'Master Angular framework with TypeScript, RxJS, and build enterprise applications.',
    shortDescription: 'Complete Angular course with TypeScript',
    category: 'Web Development',
    subcategory: 'Frontend',
    difficulty: 'Intermediate',
    duration: { hours: 50, minutes: 0 },
    instructor: { name: 'Maximilian Schwarzmüller', title: 'Angular Expert' },
    videoUrl: 'https://www.youtube.com/watch?v=3qBXWUpoPHo',
    thumbnailUrl: 'https://img.youtube.com/vi/3qBXWUpoPHo/maxresdefault.jpg',
    tags: ['Angular', 'TypeScript', 'RxJS', 'Frontend', 'SPA'],
    skills: ['Angular', 'TypeScript', 'RxJS', 'NgRx', 'Components'],
    prerequisites: ['JavaScript', 'HTML/CSS'],
    learningOutcomes: ['Build Angular apps', 'Master TypeScript', 'Use RxJS'],
    rating: { average: 4.8, count: 14800 },
    enrollments: 49300
  },
  {
    courseId: 'nextjs-react-fullstack',
    title: 'Next.js 14 & React - Full Stack Course',
    description: 'Build full stack applications with Next.js 14, React Server Components, and App Router.',
    shortDescription: 'Full stack development with Next.js 14',
    category: 'Web Development',
    subcategory: 'Full Stack',
    difficulty: 'Advanced',
    duration: { hours: 38, minutes: 30 },
    instructor: { name: 'Lee Robinson', title: 'Vercel VP' },
    videoUrl: 'https://www.youtube.com/watch?v=wm5gMKuwSYk',
    thumbnailUrl: 'https://img.youtube.com/vi/wm5gMKuwSYk/maxresdefault.jpg',
    tags: ['Next.js', 'React', 'Full Stack', 'Server Components', 'App Router'],
    skills: ['Next.js 14', 'Server Components', 'App Router', 'API Routes', 'SSR'],
    prerequisites: ['React', 'JavaScript'],
    learningOutcomes: ['Build full stack apps', 'Use Server Components', 'Deploy on Vercel'],
    rating: { average: 4.9, count: 9870 },
    enrollments: 34200,
    featured: true
  },
  {
    courseId: 'graphql-apollo-course',
    title: 'GraphQL with Apollo Complete Course',
    description: 'Master GraphQL, Apollo Client, Apollo Server, and build modern APIs.',
    shortDescription: 'GraphQL and Apollo for modern APIs',
    category: 'Web Development',
    subcategory: 'Backend',
    difficulty: 'Intermediate',
    duration: { hours: 36, minutes: 0 },
    instructor: { name: 'Eve Porcello', title: 'GraphQL Expert' },
    videoUrl: 'https://www.youtube.com/watch?v=BcLNfwF04Kw',
    thumbnailUrl: 'https://img.youtube.com/vi/BcLNfwF04Kw/maxresdefault.jpg',
    tags: ['GraphQL', 'Apollo', 'API', 'Backend', 'React'],
    skills: ['GraphQL', 'Apollo Client', 'Apollo Server', 'Schema Design', 'Resolvers'],
    prerequisites: ['JavaScript', 'REST APIs'],
    learningOutcomes: ['Build GraphQL APIs', 'Use Apollo', 'Optimize queries'],
    rating: { average: 4.7, count: 8910 },
    enrollments: 29600
  },
  {
    courseId: 'typescript-complete-course',
    title: 'TypeScript Complete Developer Course',
    description: 'Master TypeScript from basics to advanced including generics, decorators, and design patterns.',
    shortDescription: 'Complete TypeScript mastery',
    category: 'Programming Languages',
    subcategory: 'TypeScript',
    difficulty: 'Intermediate',
    duration: { hours: 34, minutes: 0 },
    instructor: { name: 'Matt Pocock', title: 'TypeScript Expert' },
    videoUrl: 'https://www.youtube.com/watch?v=30LWjhZzg50',
    thumbnailUrl: 'https://img.youtube.com/vi/30LWjhZzg50/maxresdefault.jpg',
    tags: ['TypeScript', 'JavaScript', 'Programming', 'Types'],
    skills: ['TypeScript', 'Type System', 'Generics', 'Decorators', 'Advanced Types'],
    prerequisites: ['JavaScript'],
    learningOutcomes: ['Master TypeScript', 'Use advanced types', 'Build type-safe apps'],
    rating: { average: 4.8, count: 12700 },
    enrollments: 44300
  },

  // Additional Mobile Development
  {
    courseId: 'swift-ios-development',
    title: 'iOS Development with Swift and SwiftUI',
    description: 'Build native iOS apps using Swift and SwiftUI with hands-on projects.',
    shortDescription: 'iOS development with Swift & SwiftUI',
    category: 'Mobile Development',
    subcategory: 'iOS',
    difficulty: 'Intermediate',
    duration: { hours: 54, minutes: 0 },
    instructor: { name: 'Paul Hudson', title: 'iOS Developer' },
    videoUrl: 'https://www.youtube.com/watch?v=8Xg7E9shq0U',
    thumbnailUrl: 'https://img.youtube.com/vi/8Xg7E9shq0U/maxresdefault.jpg',
    tags: ['iOS', 'Swift', 'SwiftUI', 'Mobile', 'Apple'],
    skills: ['Swift', 'SwiftUI', 'iOS Development', 'Xcode', 'App Store'],
    prerequisites: ['Basic Programming'],
    learningOutcomes: ['Build iOS apps', 'Master SwiftUI', 'Publish to App Store'],
    rating: { average: 4.8, count: 10900 },
    enrollments: 37800
  },
  {
    courseId: 'kotlin-android-development',
    title: 'Android Development with Kotlin',
    description: 'Complete Android development course using Kotlin and Jetpack Compose.',
    shortDescription: 'Android development with Kotlin',
    category: 'Mobile Development',
    subcategory: 'Android',
    difficulty: 'Intermediate',
    duration: { hours: 50, minutes: 0 },
    instructor: { name: 'Philipp Lackner', title: 'Android Developer' },
    videoUrl: 'https://www.youtube.com/watch?v=F9UC9DY-vIU',
    thumbnailUrl: 'https://img.youtube.com/vi/F9UC9DY-vIU/maxresdefault.jpg',
    tags: ['Android', 'Kotlin', 'Jetpack Compose', 'Mobile'],
    skills: ['Kotlin', 'Android', 'Jetpack Compose', 'MVVM', 'Room Database'],
    prerequisites: ['Basic Programming'],
    learningOutcomes: ['Build Android apps', 'Master Kotlin', 'Use Jetpack Compose'],
    rating: { average: 4.7, count: 13400 },
    enrollments: 46200
  },

  // Additional Game Development
  {
    courseId: 'godot-game-engine-course',
    title: 'Godot Game Engine Complete Course',
    description: 'Create 2D and 3D games using the open-source Godot Engine and GDScript.',
    shortDescription: 'Game development with Godot Engine',
    category: 'Game Development',
    subcategory: 'Godot',
    difficulty: 'Beginner',
    duration: { hours: 42, minutes: 0 },
    instructor: { name: 'Juan Linietsky', title: 'Godot Lead Developer' },
    videoUrl: 'https://www.youtube.com/watch?v=LOhfqjmasi0',
    thumbnailUrl: 'https://img.youtube.com/vi/LOhfqjmasi0/maxresdefault.jpg',
    tags: ['Godot', 'Game Development', 'GDScript', '2D Games', '3D Games'],
    skills: ['Godot Engine', 'GDScript', 'Game Design', '2D/3D Development'],
    prerequisites: ['Basic Programming'],
    learningOutcomes: ['Create games', 'Master Godot', 'Publish games'],
    rating: { average: 4.6, count: 6780 },
    enrollments: 22400
  },
  {
    courseId: 'game-dev-with-phaser',
    title: 'HTML5 Game Development with Phaser',
    description: 'Build browser-based games using Phaser 3 framework and JavaScript.',
    shortDescription: 'HTML5 games with Phaser 3',
    category: 'Game Development',
    subcategory: 'Web Games',
    difficulty: 'Intermediate',
    duration: { hours: 28, minutes: 0 },
    instructor: { name: 'Richard Davey', title: 'Phaser Creator' },
    videoUrl: 'https://www.youtube.com/watch?v=frRWKxB9Hm0',
    thumbnailUrl: 'https://img.youtube.com/vi/frRWKxB9Hm0/maxresdefault.jpg',
    tags: ['Phaser', 'HTML5', 'JavaScript', 'Game Development', 'Web Games'],
    skills: ['Phaser 3', 'JavaScript', 'Game Physics', 'Sprite Animation'],
    prerequisites: ['JavaScript'],
    learningOutcomes: ['Build web games', 'Master Phaser', 'Add game physics'],
    rating: { average: 4.5, count: 5120 },
    enrollments: 17800
  },

  // Additional Data Science
  {
    courseId: 'r-programming-data-science',
    title: 'R Programming for Data Science',
    description: 'Master R programming, ggplot2, dplyr, and statistical analysis for data science.',
    shortDescription: 'R programming and statistical analysis',
    category: 'Data Science',
    subcategory: 'R Programming',
    difficulty: 'Intermediate',
    duration: { hours: 38, minutes: 0 },
    instructor: { name: 'Roger Peng', title: 'Statistician' },
    videoUrl: 'https://www.youtube.com/watch?v=_V8eKsto3Ug',
    thumbnailUrl: 'https://img.youtube.com/vi/_V8eKsto3Ug/maxresdefault.jpg',
    tags: ['R', 'Data Science', 'Statistics', 'ggplot2', 'dplyr'],
    skills: ['R Programming', 'ggplot2', 'dplyr', 'Statistical Analysis', 'Tidyverse'],
    prerequisites: ['Basic Programming', 'Statistics'],
    learningOutcomes: ['Analyze data with R', 'Create visualizations', 'Perform statistics'],
    rating: { average: 4.6, count: 7890 },
    enrollments: 26700
  },
  {
    courseId: 'big-data-spark-hadoop',
    title: 'Big Data with Spark and Hadoop',
    description: 'Process large-scale data using Apache Spark, Hadoop, and PySpark.',
    shortDescription: 'Big data processing with Spark',
    category: 'Data Science',
    subcategory: 'Big Data',
    difficulty: 'Advanced',
    duration: { hours: 46, minutes: 0 },
    instructor: { name: 'Matei Zaharia', title: 'Spark Creator' },
    videoUrl: 'https://www.youtube.com/watch?v=9mELEARcxJo',
    thumbnailUrl: 'https://img.youtube.com/vi/9mELEARcxJo/maxresdefault.jpg',
    tags: ['Big Data', 'Spark', 'Hadoop', 'PySpark', 'Distributed Computing'],
    skills: ['Apache Spark', 'Hadoop', 'PySpark', 'Distributed Systems', 'Data Pipeline'],
    prerequisites: ['Python', 'SQL', 'Data Processing'],
    learningOutcomes: ['Process big data', 'Use Spark', 'Build data pipelines'],
    rating: { average: 4.7, count: 6540 },
    enrollments: 21900
  },

  // Additional Cloud Computing
  {
    courseId: 'google-cloud-platform-course',
    title: 'Google Cloud Platform Complete Course',
    description: 'Master GCP services including Compute Engine, Cloud Storage, BigQuery, and Kubernetes.',
    shortDescription: 'Complete Google Cloud Platform',
    category: 'Cloud Computing',
    subcategory: 'GCP',
    difficulty: 'Intermediate',
    duration: { hours: 48, minutes: 0 },
    instructor: { name: 'Google Cloud Team', title: 'Cloud Architects' },
    videoUrl: 'https://www.youtube.com/watch?v=4D3X6Xl5c_Y',
    thumbnailUrl: 'https://img.youtube.com/vi/4D3X6Xl5c_Y/maxresdefault.jpg',
    tags: ['GCP', 'Cloud Computing', 'Google Cloud', 'BigQuery', 'Kubernetes'],
    skills: ['GCP Services', 'Compute Engine', 'Cloud Storage', 'BigQuery', 'GKE'],
    prerequisites: ['Cloud Basics', 'Linux'],
    learningOutcomes: ['Use GCP services', 'Deploy applications', 'Manage cloud resources'],
    rating: { average: 4.7, count: 11200 },
    enrollments: 38400
  },
  {
    courseId: 'serverless-architecture-course',
    title: 'Serverless Architecture with AWS Lambda',
    description: 'Build scalable serverless applications using AWS Lambda, API Gateway, and DynamoDB.',
    shortDescription: 'Serverless apps with AWS Lambda',
    category: 'Cloud Computing',
    subcategory: 'Serverless',
    difficulty: 'Advanced',
    duration: { hours: 34, minutes: 0 },
    instructor: { name: 'Yan Cui', title: 'Serverless Expert' },
    videoUrl: 'https://www.youtube.com/watch?v=EBSdyoO3goc',
    thumbnailUrl: 'https://img.youtube.com/vi/EBSdyoO3goc/maxresdefault.jpg',
    tags: ['Serverless', 'AWS Lambda', 'API Gateway', 'DynamoDB', 'Cloud'],
    skills: ['AWS Lambda', 'API Gateway', 'DynamoDB', 'Serverless Framework', 'Event-Driven'],
    prerequisites: ['AWS Basics', 'Node.js'],
    learningOutcomes: ['Build serverless apps', 'Use Lambda functions', 'Design event-driven systems'],
    rating: { average: 4.8, count: 7650 },
    enrollments: 26800
  },

  // Additional DevOps
  {
    courseId: 'cicd-jenkins-gitlab',
    title: 'CI/CD with Jenkins and GitLab',
    description: 'Master continuous integration and deployment using Jenkins, GitLab CI, and automation.',
    shortDescription: 'CI/CD pipelines and automation',
    category: 'DevOps',
    subcategory: 'CI/CD',
    difficulty: 'Intermediate',
    duration: { hours: 36, minutes: 0 },
    instructor: { name: 'Kohsuke Kawaguchi', title: 'Jenkins Creator' },
    videoUrl: 'https://www.youtube.com/watch?v=scEDHsr3APg',
    thumbnailUrl: 'https://img.youtube.com/vi/scEDHsr3APg/maxresdefault.jpg',
    tags: ['CI/CD', 'Jenkins', 'GitLab', 'DevOps', 'Automation'],
    skills: ['Jenkins', 'GitLab CI', 'Pipeline Automation', 'Testing', 'Deployment'],
    prerequisites: ['Git', 'Linux', 'Basic DevOps'],
    learningOutcomes: ['Build CI/CD pipelines', 'Automate deployments', 'Implement best practices'],
    rating: { average: 4.6, count: 9870 },
    enrollments: 33200
  },
  {
    courseId: 'terraform-infrastructure-code',
    title: 'Terraform - Infrastructure as Code',
    description: 'Learn infrastructure automation with Terraform for AWS, Azure, and GCP.',
    shortDescription: 'Infrastructure as code with Terraform',
    category: 'DevOps',
    subcategory: 'Infrastructure',
    difficulty: 'Intermediate',
    duration: { hours: 32, minutes: 0 },
    instructor: { name: 'Mitchell Hashimoto', title: 'Terraform Creator' },
    videoUrl: 'https://www.youtube.com/watch?v=l5k1ai_GBDE',
    thumbnailUrl: 'https://img.youtube.com/vi/l5k1ai_GBDE/maxresdefault.jpg',
    tags: ['Terraform', 'IaC', 'DevOps', 'Cloud', 'Automation'],
    skills: ['Terraform', 'Infrastructure as Code', 'Cloud Automation', 'Multi-Cloud'],
    prerequisites: ['Cloud Basics', 'Linux'],
    learningOutcomes: ['Automate infrastructure', 'Use Terraform', 'Manage cloud resources'],
    rating: { average: 4.8, count: 10200 },
    enrollments: 35600
  },

  // Additional Cybersecurity
  {
    courseId: 'network-security-fundamentals',
    title: 'Network Security Fundamentals',
    description: 'Learn network security, firewalls, VPNs, IDS/IPS, and secure network design.',
    shortDescription: 'Network security and protection',
    category: 'Cybersecurity',
    subcategory: 'Network Security',
    difficulty: 'Intermediate',
    duration: { hours: 40, minutes: 0 },
    instructor: { name: 'Bruce Schneier', title: 'Security Expert' },
    videoUrl: 'https://www.youtube.com/watch?v=JDM-fo-i6dk',
    thumbnailUrl: 'https://img.youtube.com/vi/JDM-fo-i6dk/maxresdefault.jpg',
    tags: ['Network Security', 'Firewalls', 'VPN', 'IDS', 'Security'],
    skills: ['Network Security', 'Firewalls', 'VPN', 'IDS/IPS', 'Packet Analysis'],
    prerequisites: ['Networking Basics'],
    learningOutcomes: ['Secure networks', 'Configure firewalls', 'Implement VPNs'],
    rating: { average: 4.7, count: 8920 },
    enrollments: 30400
  },

  // Additional Programming Languages
  {
    courseId: 'go-programming-complete',
    title: 'Go Programming Complete Course',
    description: 'Master Go (Golang) programming for building high-performance applications and microservices.',
    shortDescription: 'Complete Go programming course',
    category: 'Programming Languages',
    subcategory: 'Go',
    difficulty: 'Intermediate',
    duration: { hours: 36, minutes: 0 },
    instructor: { name: 'Rob Pike', title: 'Go Co-Creator' },
    videoUrl: 'https://www.youtube.com/watch?v=YS4e4q9oBaU',
    thumbnailUrl: 'https://img.youtube.com/vi/YS4e4q9oBaU/maxresdefault.jpg',
    tags: ['Go', 'Golang', 'Programming', 'Backend', 'Microservices'],
    skills: ['Go Programming', 'Concurrency', 'Goroutines', 'Microservices', 'REST APIs'],
    prerequisites: ['Basic Programming'],
    learningOutcomes: ['Master Go', 'Build microservices', 'Handle concurrency'],
    rating: { average: 4.8, count: 10100 },
    enrollments: 34800
  },
  {
    courseId: 'rust-programming-course',
    title: 'Rust Programming Complete Course',
    description: 'Learn Rust programming for systems programming, memory safety, and performance.',
    shortDescription: 'Systems programming with Rust',
    category: 'Programming Languages',
    subcategory: 'Rust',
    difficulty: 'Advanced',
    duration: { hours: 44, minutes: 0 },
    instructor: { name: 'Steve Klabnik', title: 'Rust Expert' },
    videoUrl: 'https://www.youtube.com/watch?v=MsocPEZBd-M',
    thumbnailUrl: 'https://img.youtube.com/vi/MsocPEZBd-M/maxresdefault.jpg',
    tags: ['Rust', 'Systems Programming', 'Memory Safety', 'Performance'],
    skills: ['Rust', 'Ownership', 'Borrowing', 'Systems Programming', 'WebAssembly'],
    prerequisites: ['C/C++', 'Programming Basics'],
    learningOutcomes: ['Master Rust', 'Write safe code', 'Build performant systems'],
    rating: { average: 4.9, count: 6780 },
    enrollments: 23400
  },
  {
    courseId: 'java-complete-masterclass',
    title: 'Java Programming Complete Masterclass',
    description: 'Complete Java course from basics to advanced including Spring Boot and microservices.',
    shortDescription: 'Master Java and Spring Boot',
    category: 'Programming Languages',
    subcategory: 'Java',
    difficulty: 'Beginner',
    duration: { hours: 60, minutes: 0 },
    instructor: { name: 'Tim Buchalka', title: 'Java Expert' },
    videoUrl: 'https://www.youtube.com/watch?v=grEKMHGYyns',
    thumbnailUrl: 'https://img.youtube.com/vi/grEKMHGYyns/maxresdefault.jpg',
    tags: ['Java', 'Spring Boot', 'Programming', 'Backend', 'OOP'],
    skills: ['Java', 'OOP', 'Spring Boot', 'JPA', 'Microservices'],
    prerequisites: ['None'],
    learningOutcomes: ['Master Java', 'Build Spring apps', 'Create microservices'],
    rating: { average: 4.7, count: 24500 },
    enrollments: 85600,
    featured: true
  },

  // Additional Database
  {
    courseId: 'postgresql-complete-course',
    title: 'PostgreSQL Complete Developer Course',
    description: 'Master PostgreSQL database including advanced queries, indexing, and performance tuning.',
    shortDescription: 'Complete PostgreSQL mastery',
    category: 'Database',
    subcategory: 'SQL',
    difficulty: 'Intermediate',
    duration: { hours: 36, minutes: 0 },
    instructor: { name: 'Hussein Nasser', title: 'Database Expert' },
    videoUrl: 'https://www.youtube.com/watch?v=qw--VYLpxG4',
    thumbnailUrl: 'https://img.youtube.com/vi/qw--VYLpxG4/maxresdefault.jpg',
    tags: ['PostgreSQL', 'SQL', 'Database', 'Performance', 'Indexing'],
    skills: ['PostgreSQL', 'Advanced SQL', 'Indexing', 'Query Optimization', 'JSONB'],
    prerequisites: ['SQL Basics'],
    learningOutcomes: ['Master PostgreSQL', 'Optimize queries', 'Design efficient databases'],
    rating: { average: 4.8, count: 9870 },
    enrollments: 33400
  },
  {
    courseId: 'redis-caching-course',
    title: 'Redis - The Complete Developer Course',
    description: 'Master Redis for caching, session management, and real-time applications.',
    shortDescription: 'Redis for caching and real-time apps',
    category: 'Database',
    subcategory: 'NoSQL',
    difficulty: 'Intermediate',
    duration: { hours: 24, minutes: 0 },
    instructor: { name: 'Salvatore Sanfilippo', title: 'Redis Creator' },
    videoUrl: 'https://www.youtube.com/watch?v=jgpVdJB2sKQ',
    thumbnailUrl: 'https://img.youtube.com/vi/jgpVdJB2sKQ/maxresdefault.jpg',
    tags: ['Redis', 'Caching', 'NoSQL', 'In-Memory', 'Performance'],
    skills: ['Redis', 'Caching', 'Session Management', 'Pub/Sub', 'Data Structures'],
    prerequisites: ['Database Basics'],
    learningOutcomes: ['Use Redis effectively', 'Implement caching', 'Build real-time features'],
    rating: { average: 4.7, count: 7230 },
    enrollments: 24800
  },

  // Additional UI/UX
  {
    courseId: 'figma-ui-design-advanced',
    title: 'Advanced UI Design with Figma',
    description: 'Master advanced Figma techniques, design systems, auto-layout, and collaborative design.',
    shortDescription: 'Advanced Figma and design systems',
    category: 'UI/UX Design',
    subcategory: 'UI Design',
    difficulty: 'Advanced',
    duration: { hours: 32, minutes: 0 },
    instructor: { name: 'Gary Simon', title: 'UI Designer' },
    videoUrl: 'https://www.youtube.com/watch?v=HZuk6Wkx_Eg',
    thumbnailUrl: 'https://img.youtube.com/vi/HZuk6Wkx_Eg/maxresdefault.jpg',
    tags: ['Figma', 'UI Design', 'Design Systems', 'Auto Layout', 'Prototyping'],
    skills: ['Advanced Figma', 'Design Systems', 'Auto Layout', 'Components', 'Variables'],
    prerequisites: ['Figma Basics', 'UI Design'],
    learningOutcomes: ['Create design systems', 'Master auto layout', 'Build advanced prototypes'],
    rating: { average: 4.8, count: 8910 },
    enrollments: 29700
  },

  // Additional Software Engineering
  {
    courseId: 'software-architecture-patterns',
    title: 'Software Architecture and Design Patterns',
    description: 'Master software architecture, design patterns, SOLID principles, and system design.',
    shortDescription: 'Software architecture and design patterns',
    category: 'Software Engineering',
    subcategory: 'Architecture',
    difficulty: 'Advanced',
    duration: { hours: 40, minutes: 0 },
    instructor: { name: 'Martin Fowler', title: 'Software Architect' },
    videoUrl: 'https://www.youtube.com/watch?v=FLtqAi7WNBY',
    thumbnailUrl: 'https://img.youtube.com/vi/FLtqAi7WNBY/maxresdefault.jpg',
    tags: ['Software Architecture', 'Design Patterns', 'SOLID', 'System Design'],
    skills: ['Architecture Patterns', 'Design Patterns', 'SOLID Principles', 'System Design'],
    prerequisites: ['OOP', 'Programming Experience'],
    learningOutcomes: ['Design scalable systems', 'Apply design patterns', 'Follow best practices'],
    rating: { average: 4.9, count: 11200 },
    enrollments: 38900
  },
  {
    courseId: 'microservices-architecture-course',
    title: 'Microservices Architecture Complete Course',
    description: 'Build scalable microservices using Docker, Kubernetes, and API Gateway patterns.',
    shortDescription: 'Microservices with Docker & K8s',
    category: 'Software Engineering',
    subcategory: 'Microservices',
    difficulty: 'Advanced',
    duration: { hours: 48, minutes: 0 },
    instructor: { name: 'Chris Richardson', title: 'Microservices Expert' },
    videoUrl: 'https://www.youtube.com/watch?v=CZ3wIuvmHeM',
    thumbnailUrl: 'https://img.youtube.com/vi/CZ3wIuvmHeM/maxresdefault.jpg',
    tags: ['Microservices', 'Docker', 'Kubernetes', 'Architecture', 'Distributed Systems'],
    skills: ['Microservices', 'Docker', 'Kubernetes', 'API Gateway', 'Service Mesh'],
    prerequisites: ['Backend Development', 'Docker', 'APIs'],
    learningOutcomes: ['Design microservices', 'Deploy with K8s', 'Handle distributed systems'],
    rating: { average: 4.8, count: 10300 },
    enrollments: 35700
  }
];

const seedCourses = async () => {
  try {
    // Connect to MongoDB
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    // Clear existing courses
    await Course.deleteMany({});
    console.log('Cleared existing courses');

    // Insert courses
    await Course.insertMany(courses);
    console.log(`Successfully seeded ${courses.length} courses`);

    // Print summary
    const categoryCounts = await Course.aggregate([
      { $group: { _id: '$category', count: { $sum: 1 } } },
      { $sort: { count: -1 } }
    ]);

    console.log('\nCourses by Category:');
    categoryCounts.forEach(cat => {
      console.log(`  ${cat._id}: ${cat.count} courses`);
    });

    mongoose.connection.close();
    console.log('\nDatabase connection closed');
  } catch (error) {
    console.error('Error seeding courses:', error);
    process.exit(1);
  }
};

seedCourses();
